# Generated by Django 4.0.2 on 2022-02-27 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_guest_can_pause_room_allow_others_to_edit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='announcements',
            field=models.TextField(default='No announcements'),
        ),
    ]
