# Generated by Django 4.0.2 on 2022-02-27 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_room_announcements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='host_key',
            field=models.CharField(max_length=50),
        ),
    ]
