# Generated by Django 4.0.2 on 2022-02-27 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_room_announcements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='announcements',
            field=models.TextField(default='[]'),
        ),
    ]
